### ISSUE TITLE
Create end-to-end pipeline integrating all functionalities

### ISSUE THREAD

**Issue by RigvedManoj** [RigvedManoj/FaceMatch#13]
**Description:**

Add two client facing functionalities (bulk_upload and match_face) that take in input and give output. Integrate with complete pipeline to load to database and match with images in database.  

**Tasks:**

 - [x] Write unit testcase for implemented bulk_upload functionality.
 - [x] Create face matching functionality (match_face) to compare an input image against images stored in the database.
 - [x] Write unit testcase for implemented match_face functionality.
 - [x] Integrate both the bulk upload and face matching functionalities into the existing pipeline for end-to-end processing.
 - [x] Write unit testcases for end-to-end testing.
