### ISSUE TITLE
Implement Similarity Search in Database with FAISS

### ISSUE THREAD

**Issue by anjus1313** [RigvedManoj/FaceMatch#17]
**Description:**
To implement similarity search feature in the database using FAISS (Facebook AI Similarity Search). This will enable efficient searching and retrieval of relevant images based on face vector embeddings.

**Tasks:**
- [x] Embedding storage: Check if storing the embeddings in a csv file is the efficient and compatible with FAISS.
- [x] Implement a working FAISS-based similarity search feature.
- [x] Write unit test cases for each function.
