### ISSUE TITLE
Research for Face Recognition Model for Embedding Generation

### ISSUE THREAD

**Issue by anjus1313** [RigvedManoj/FaceMatch#3]
**Description**
Research various state-of-the-art face recognition models that generate face embeddings. The objective is to compare their performance in terms of accuracy, embedding size, computational complexity, and scalability for integration into a large-scale face recognition system.

**Tasks**
- [x] Research models that do face embedding generation
- [x] Tabulate key metrics for each of the models
- [x] Prepare a comparison table

**Deliverable**
A comparison table summarizing the performance of various face recognition models, along with recommendations for the best-suited model for large-scale systems.

**Comment by anjus1313** [comment]
The attached doc contains model analysis and comparison.

https://docs.google.com/document/d/1CpN__oPgmAvY65s-tWg4X-pZPCPwNEAU-ULrkdKWES4/edit?usp=sharing

**Comment by anjus1313** [comment]
The attached doc contains model analysis and comparison.

https://docs.google.com/document/d/1CpN__oPgmAvY65s-tWg4X-pZPCPwNEAU-ULrkdKWES4/edit?usp=sharing
